# This is a basic workflow that is manually triggered

name: Create Release

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [ "main" ]
    tags:
      -  "v*.*"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  create-release:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    # Runs a single command using the runners shell
    - name: Download latest compiler
      uses: robinraju/release-downloader@v1
      with:
        repository: Ryxali/DomCompiler
        latest: true
        fileName: 'DomCompiler-win-x64.zip'

    - name: Unzip
      run: 7z x DomCompiler-win-x64.zip
    
    - name: Execute
      run: ${{ format('.\DomCompiler-win-x64\DomCompiler.exe {0}\Dun\Dun.dm Dun', runner.temp) }}
  
    - name: Zip
      run: ${{ format('7z a {0}\Dun.zip {0}\Dun\*', runner.temp) }}

    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      uses: softprops/action-gh-release@v2
      with:
        body_path: ReleaseStub.md
        draft: true
        files: ${{ format('{0}\Dun.zip', runner.temp) }}